---
title: "Dominant weeds"
author: "Jackie"
date: "2023-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(dplyr)
library(ggplot2)
library(plotly)
library(ggpubr)


```

## Import data



```{r import the data, echo=FALSE, message=FALSE, warning=FALSE}
HR_weed_list <-  read_excel("W:/Economic impact of weeds round 2/HR/raw_data/Weed Species locations no co-ordinates.xlsx", 
                                                     sheet = "NSW")
## make it long
#str(HR_weed_list)
HR_weed_list <- HR_weed_list%>%  dplyr::select(Sample:Wireweed)
#str(HR_weed_list)
HR_weed_list <- HR_weed_list %>%  rename(AEZ = `GRDC AEZ`)

HR_weed_list_long <- pivot_longer(HR_weed_list,
                                  cols = c(`3 corner Jack`:`Wireweed`),
                                  names_to = "weed",
                                  values_to="weed_class"
                                  )

#unique(HR_weed_list_long$weed_class)

## recode weed class with an number
HR_weed_list_long <-HR_weed_list_long %>% 
  mutate(
    weed_class_code = case_when(
      weed_class =="VL" ~ "1",
      weed_class =="L" ~ "2",
      weed_class =="M" ~ "3",
      weed_class =="H" ~ "4",
      TRUE ~ weed_class
    )
  )


## remove all the rows with missing weeds
HR_weed_list_long_remove_na <- HR_weed_list_long %>% filter(!is.na(weed_class))
```

## List of weeds per AEZ 


```{r List of weeds per AEZ, echo=FALSE, message=TRUE, warning=FALSE}
################################################################################
### make a list of weeds per zone
#str(HR_weed_list_long_remove_na)

list_of_weed_AEZ <- HR_weed_list_long_remove_na %>% 
  group_by(AEZ) %>% 
  distinct(weed, .keep_all = TRUE) %>% 
  select(AEZ, weed)
  
list_of_weed_AEZ <- ungroup(list_of_weed_AEZ)
#str(list_of_weed_AEZ)

#write.csv(list_of_weed_AEZ, "W:/Economic impact of weeds round 2/HR/Jackie_working/Weed_list/list_of_weed_AEZ.csv", row.names = FALSE)


```
## how many weeds ID per zone

```{r count of weeds list per AEZ, echo=FALSE, message=FALSE, warning=FALSE}
################################################################################
list_of_weed_AEZ_count <- list_of_weed_AEZ %>% count(AEZ)    



list_of_weed_AEZ_count <- list_of_weed_AEZ_count %>% rename(`Number of weeds ID` = n)

list_of_weed_AEZ_count
#write.csv(list_of_weed_AEZ_count, "W:/Economic impact of weeds round 2/HR/Jackie_working/Weed_list/list_of_weed_AEZ_count.csv", row.names = FALSE)

```
## how many paddcoks per zone and year

```{r count of paddock per year and zone, echo=FALSE, message=FALSE, warning=FALSE}
################################################################################
paddock_per_AEZ_year <- HR_weed_list_long_remove_na %>%  count(Sample, AEZ, Year) #nope this is not what I want

paddock_per_AEZ_year <- paddock_per_AEZ_year %>% 
  group_by(AEZ, Year) %>% 
  count(AEZ)

paddock_per_AEZ_year <- ungroup(paddock_per_AEZ_year)
#str(paddock_per_AEZ_year)
paddock_per_AEZ_year <- paddock_per_AEZ_year %>%  rename(`count of paddocks` = n)


paddock_per_AEZ_year

```

## Rank of weeds per AEZ / year based on all paddocks sampled in that year / AEZ
Also calculating the % of weed in all the paddocks sampled (e.g per AEZ and paddock) 

```{r Rank and occurance cals, echo=FALSE, message=FALSE, warning=FALSE}

################################################################################
#count the number of weed occurrence per AEZ, weed and year  
AEZ_weeds_count <- HR_weed_list_long_remove_na %>% count(AEZ, weed, Year, sort = TRUE)    
AEZ_weeds_count <- AEZ_weeds_count %>%  arrange(AEZ, weed, Year)
#str(AEZ_weeds_count) 
AEZ_weeds_count <- AEZ_weeds_count %>%  rename(count = n)

#count the number of paddocks sampled per AEZ and year (from above)
#paddock_per_AEZ_year



################################################################################
#### join the summary data together
AEZ_weeds <- left_join(AEZ_weeds_count,paddock_per_AEZ_year)
## add a percent 

#str(AEZ_weeds)
AEZ_weeds <- AEZ_weeds %>% mutate(percent_occurance = (count/`count of paddocks`)*100) 
AEZ_weeds$percent_occurance <- round(AEZ_weeds$percent_occurance, 2)

#AEZ_weeds

################################################################################
## add a rank ## ranks without averaging # first occurrence wins
#str(AEZ_weeds)

AEZ_weeds <- AEZ_weeds %>% arrange(AEZ, Year) %>%
  group_by(AEZ, Year) %>%
  mutate(rank = rank(-percent_occurance, ties.method= "first"))


################################################################################
# keep the top 4 weeds in each AEZ and year

top4weeds <- AEZ_weeds %>% 
  group_by(AEZ, Year) %>%
  top_n(-4, rank)
top4weeds <- top4weeds %>%  select(AEZ, Year, weed, percent_occurance, rank)
top4weeds$percent_occurance <- round(top4weeds$percent_occurance, 0)
top4weeds <- top4weeds %>% arrange(AEZ, Year, rank)

top4weeds
```


# Plots of weed desnisties for weed 1 and 2 per AEZ / year



```{r Rank and occurance cals, echo=FALSE, message=FALSE, warning=FALSE}

################################################################################
#Addd ranking to the long list of weeds

rank1_2 <- top4weeds %>% filter(rank == 1 | rank==2) 
rank <- left_join(HR_weed_list_long_remove_na, rank1_2)
## remove all the rows with missing weeds
rank <- rank %>% filter(!is.na(rank))
# str(rank)
# unique(rank$weed_class)

rank$weed_class <- as.factor(rank$weed_class)
#levels(rank$weed_class)
rank$weed_class <- factor(rank$weed_class, levels=c("VL", "L", "M", "H", "VH"))

label_weed1 <- rank %>% 
  filter(rank == 1) %>% 
  distinct(Year,AEZ, .keep_all = TRUE)

label_weed2 <- rank %>% 
  filter(rank == 2) %>% 
  distinct(Year,AEZ, .keep_all = TRUE)


### Plot of weed 1 and 2
rank %>% 
 filter(rank == 1) %>% 
ggplot(aes(as.factor(Year),  weed_class))+
  geom_jitter(aes(colour = weed_class), position=position_jitter(0.2))+
   facet_wrap(.~AEZ)+
   geom_text(data=label_weed1, mapping = aes(label=stringr::str_wrap(weed,4),y="VH",x=as.factor(Year)), angle = 90, size =3, colour= "black")+
   theme_bw()+ 
   labs(title = "Most common weed by AEZ and Year",
        subtitle = "Rank weed 1",
        caption = "Using: Weed Species locations no co-ordinates.xlsx",
        x = "Year",  
       y ="Weed Class")+
   theme(legend.position = "none")+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))


rank %>% 
  filter(rank == 2) %>% 
  ggplot(aes(as.factor(Year),  weed_class))+
  geom_jitter(aes(colour = weed_class), position=position_jitter(0.2))+
  facet_wrap(.~AEZ)+
  geom_text(data=label_weed2, mapping = aes(label=stringr::str_wrap(weed,4),y="VH",x=as.factor(Year)), angle = 90, size =3, colour= "black")+
  theme_bw()+ 
  labs(title = "Most common weed by AEZ and Year",
       subtitle = "Rank weed 2",
       caption = "Using: Weed Species locations no co-ordinates.xlsx",
       x = "Year",  
       y ="Weed Class")+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

##################################################################################

```


Add the summaries mode data to the plots and chcek its good


```{r mode, echo=FALSE, message=FALSE, warning=FALSE}

################################################################################
##################################################################################

###summaries the weed class   
#str(rank)

rank$weed_class_code <- as.double(rank$weed_class_code)
#I need a function to cal mode!
mode <- function(codes){
  which.max(tabulate(codes))
}

rank_AEZ_weed_densities <- rank %>% 
  group_by(weed, AEZ, Year, rank) %>% 
  summarise(
    mode =mode(weed_class_code),
    median = median(weed_class_code, na.rm = TRUE)
  ) %>% 
  arrange(AEZ, rank, Year )


################################################################################
#str(rank_AEZ_weed_densities)
rank_AEZ_weed_densities <- ungroup(rank_AEZ_weed_densities)

### add the mode and median back into the rank data 
rank_density_mode <- left_join(rank, rank_AEZ_weed_densities)

rank_density_mode_display_weed1 <- rank_density_mode %>% 
  filter(rank == 1) %>% 
  distinct(Year,AEZ, .keep_all = TRUE) %>% select(Year,AEZ, mode)
rank_density_mode_display_weed2 <- rank_density_mode %>% 
  filter(rank == 2) %>% 
  distinct(Year,AEZ, .keep_all = TRUE) %>% select(Year,AEZ, mode)

### recode mode.

## recode weed class with an number
rank_density_mode_display_weed1 <-rank_density_mode_display_weed1 %>% 
  mutate(
    weed_class_Mode = case_when(
      mode ==1 ~ "VL",
      mode ==2 ~ "L",
      mode ==3 ~ "M",
      mode ==4~ "H",
      mode ==5 ~ "VH",
      TRUE ~ "check"
    )
  )

rank_density_mode_display_weed2 <-rank_density_mode_display_weed2 %>% 
  mutate(
    weed_class_Mode = case_when(
      mode ==1 ~ "VL",
      mode ==2 ~ "L",
      mode ==3 ~ "M",
      mode ==4~ "H",
      mode ==5 ~ "VH",
      TRUE ~ "check"
    )
  )
#turn it into a factor so it displays better
rank_density_mode_display_weed1$weed_class_Mode <- as.factor(rank_density_mode_display_weed1$weed_class_Mode)
levels(rank_density_mode_display_weed1$weed_class_Mode)
rank_density_mode_display_weed1$weed_class_Mode <- factor(rank_density_mode_display_weed1$weed_class_Mode, levels=c("VL", "L", "M", "H", "VH"))

rank_density_mode_display_weed2$weed_class_Mode <- as.factor(rank_density_mode_display_weed2$weed_class_Mode)
levels(rank_density_mode_display_weed2$weed_class_Mode)
rank_density_mode_display_weed2$weed_class_Mode <- factor(rank_density_mode_display_weed2$weed_class_Mode, levels=c("VL", "L", "M", "H", "VH"))

### Plot of weed 1 and 2
rank1_plot <- rank_density_mode %>% 
  filter(rank == 1) %>% 
  ggplot(aes(as.factor(Year),  weed_class))+
  #geom_point(data = rank_density_mode_display_weed1, aes(as.factor(Year),  weed_class_Mode))+
  geom_jitter(aes(colour = weed_class), position=position_jitter(0.2))+
  facet_wrap(.~AEZ)+
  geom_text(data=label_weed1, mapping = aes(label=stringr::str_wrap(weed,4),y="VH",x=as.factor(Year)), angle = 90, size =3, colour= "black")+
  theme_bw()+ 
  labs(title = "Most common weed by AEZ and Year",
       subtitle = "Rank weed 1, mode of densisty in black",
       caption = "Using: Weed Species locations no co-ordinates.xlsx",
       x = "Year",  
       y ="Weed Class")+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
### Add the mode data
rank1_plot + geom_point(data = rank_density_mode_display_weed1, aes(as.factor(Year),  weed_class_Mode))

  
 

### Plot of weed 1 and 2
rank2_plot <- rank_density_mode %>% 
  filter(rank == 2) %>% 
  ggplot(aes(as.factor(Year),  weed_class))+
  #geom_point(data = rank_density_mode_display_weed1, aes(as.factor(Year),  weed_class_Mode))+
  geom_jitter(aes(colour = weed_class), position=position_jitter(0.2))+
  facet_wrap(.~AEZ)+
  geom_text(data=label_weed2, mapping = aes(label=stringr::str_wrap(weed,4),y="VH",x=as.factor(Year)), angle = 90, size =3, colour= "black")+
  theme_bw()+ 
  labs(title = "Most common weed by AEZ and Year",
       subtitle = "Rank weed 2, mode of densisty in black",
       caption = "Using: Weed Species locations no co-ordinates.xlsx",
       x = "Year",  
       y ="Weed Class")+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

### Add the mode data
rank2_plot + geom_point(data = rank_density_mode_display_weed2, aes(as.factor(Year),  weed_class_Mode))


```